version: '3.8'

services:
  rabbitmq:
    container_name: rabbitmq
    restart: on-failure
    image: rabbitmq:3.12.3-management-alpine
    ports:
      - "15673:15672"
      - "5673:5672"
    volumes:
      - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"