version: '3.8'

services:

  logstash:
    container_name: logstash
    build:
      context: ./logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "8080:8080"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      cluster.name: "docker-cluster"
      network.host: 0.0.0.0
      discovery.type: single-node
      xpack.security.enabled: false

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.4
    container_name: kibana
    environment:
      server.name: kibana
      server.host: "0"
      elasticsearch.url: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
