version: "3.8"
services:
  selenium:
    container_name: selenium
    restart: on-failure
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
    volumes:
      - ./frontend_test/shm:/dev/shm selenium/standalone-chrome