version: '3.9'

services:
  frontend:
    container_name: frontend
    restart: on-failure
    build:
      context: ./src/Frontend
      dockerfile: Dockerfile
    ports:
      - 5012:80
    environment:
      - API_HOST="http://127.0.0.1:5012"

  selenium:
    container_name: selenium
    restart: on-failure
    image: selenium/standalone-firefox:4.9.0
    ports:
      - 4444:4444
      - 7900:7900
  bookingapi:
    container_name: bookingapi
    restart: on-failure
    build:
      context: ./src/BookingApi
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 40080:80

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./test-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

  pgadmin:
    image: dpage/pgadmin4:7
    environment:
      PGADMIN_DEFAULT_EMAIL: don-sbn@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: mysecretpassword
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - ./pgadmin-config/servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres
