FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /App

# Copy everything

COPY ./ContentEnricher ./

# Restore as distinct layers
RUN dotnet restore
# Build and publish a release

ENTRYPOINT ["dotnet", "run"]