name: Test

on: [pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore test dependencies
      run: dotnet restore ./src/src/BookingApi/BookingApi/BookingApi.xUnitTests.csproj
    - name: Build test project
      run: dotnet build ./src/src/BookingApi/BookingApi/BookingApi.xUnitTests.csproj --no-restore
    - name: Test
      run: dotnet test ./src/src/BookingApi/BookingApi/BookingApi.xUnitTests.csproj --no-build --verbosity normal

      